### ISSUE TITLE
能否提交至插件商店？

### ISSUE THREAD

**Issue by padoru233** [sansenhoshi/nonebot_plugin_helldivers_tools#1]
我写出了一种基于战备类型：红/蓝/绿的随机规则，能否pr和提交到商店，希望能完成这个项目

**Comment by sansenhoshi** [comment]
插件商店那个我不会弄，代码已经合并了

**Comment by sansenhoshi** [comment]
感谢🙏

**Comment by sansenhoshi** [comment]
那个应该是用playwright暴力替换文本导致的，那个功能其实有更好的解决办法就是需要构建一个hd2的api，那样就可以直接使用api的数据来渲染一个图片而不是从其他网站截图，后面我研究一下那个api 的构建吧

**Comment by sansenhoshi** [comment]
api我之前搭建了一个就是没有返回数据，可能是有什么部分没弄好，我找时间再看看，如果这个功能用的不多其实可以用英文版，我是给所有的星球的中文都对应了一遍，然后把截图的网页里面对应的星球都替换成了中文，如果不用应该可以把这部分注释掉，性能应该可以提升很多
![image](https://github.com/user-attachments/assets/f6271dca-5ac4-4311-b4ff-d46d43ead75c)

**Comment by sansenhoshi** [comment]
好了，你看看

**Comment by sansenhoshi** [comment]
https://pypi.org/project/nonebot-plugin-helldivers-tools/
